- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
          - url: https://github.com/Jeeseob/DataYouthCampus2021
- name: Java
  logo: Java
  url: https://developer.android.com/
  color: '#3DDC84'
  projects:
          - url: https://github.com/Jeeseob/SoftwareEngineering
          
