- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
          - url: https://github.com/Jeeseob/DataYouthCampus2021
- name: Android
  logo: Android
  url: https://developer.android.com/
  color: '#3DDC84'
  projects:
          - url: https://github.com/Jeeseob/SoftwareEngineering
- name: SpringBoot
  logo: SpringBoot
  url: https://spring.io/
  color: '#6DB33F'
  projects:
          - url: https://github.com/Jeeseob/Engineering_Design_Student_Self_Grading
- name: Ubuntu
  logo: Ubuntu
  url: https://ubuntu.com/download/desktop
  color: '#E95420'
  projects:
          - url: https://github.com/Jeeseob/Unix_Socket_Omok
